### ISSUE TITLE
Name of tool needs to be changed to Geospatial and Information Substitution and Anonymization Tool (GISA)

### ISSUE THREAD

**Issue by paigemork** [NETL-RIC/GISA-testing-issues#1]
Top bar of tool says "Geologically Informed Spatial Anonymizer (GISA)" when opened. Tool name needs to be changed to "Geospatial and Information Substitution and Anonymization Tool (GISA)". See top of image for example. 
![Removal_Term_Entered](https://github.com/NETL-RIC/GISA-testing-issues/assets/56645312/76c94d85-ed12-4076-979b-b21313a6016b)

**Comment by michael-c-gao** [comment]
fixed
