### ISSUE TITLE
Integration of hydrologic parameters in base anonymization code for point shapefiles

### ISSUE THREAD

**Issue by paigemork** [NETL-RIC/GISA-testing-issues#13]
Consider using the hydrologic data - rivers, lakes, water bodies, and ocean - to define where not to put points for any data anonymization of point data. 

So as a base code for all data anonymization of points, no matter method (LSH, Cluster, or Buffer), points could not be relocated into the bounds of polygons represented by water ways, lakes, water bodies, etc.
Shapefiles from the data anonymization factors that could be used for this:
NHDFlowline
NHDWaterbody 
There may also be a shapefile on GAIA for the world oceans....or published by USGS we could track down.

**Comment by justaPCWingo** [comment]
@michael-c-gao how easy is it to add additional layers?

**Comment by michael-c-gao** [comment]
For the buffer anonymization for shapefiles adding it will be simple, but for the other methods such as LSH it will probably be pretty difficult.

**Comment by justaPCWingo** [comment]
working on this now. Added a world-seas layer, which should add buffers for oceans and seas.

**Comment by justaPCWingo** [comment]
layers added to buffer anonymization. LSH application is on hold
