### ISSUE TITLE
Cannot get any layers to work with Buffer anonymization other than Census Tracts, or with inclusion of Census_Tracts layer 

### ISSUE THREAD

**Issue by paigemork** [NETL-RIC/GISA-testing-issues#14]
**Describe the bug**
Program fully shuts down every time I attempt to use the Buffer Anonymization with any layer other than Census Tract. 
However, it does work if I select Census Tract layer and other layers. 

**To Reproduce**
1. Select Data > CarbonSAFE_Projects_60_Points.shp
2. Select any Layers other than Census_Tract
3. Select Buffer Anonymization 
4. "Plot Data" 
5. GISA program shuts down 

Or 
1. Select Data > CarbonSAFE_Projects_60_Points.shp
2. Select any Layers ALONG WITH Census_Tract
3. Select Buffer Anonymization 
4. "Plot Data" 
5. Takes awhile but eventually draws. 

**Expected behavior**
I would expect that I do not need to select census tract layer in order to run buffer anonymization. Should enable us to select one or multiple without selecting census tract to work. 

**Screenshots**

** Stack Trace **
Example trying to use Oil_Gas_Atalas5_v3_Final as only layer:

{'Oil_Gas_Atlas5_v3_final'}
C:\Users\morknerp\Downloads\gisa\_internal\gisalib/controllers/Contraints_Oct2023.gdb
EPSG:4326
Traceback (most recent call last):
  File "gisalib\ui_qt\location_tab.py", line 188, in _refresh_map
  File "gisalib\controllers\location_controller.py", line 198, in apply_buffer
  File "gisalib\controllers\LocationAnonymizer.py", line 54, in apply_constraint
KeyError: 'Census_Tract'

**Comment by michael-c-gao** [comment]
fixed, no more census keyerrors
