### ISSUE TITLE
Improve function of selection of Layers for buffer anonymization

### ISSUE THREAD

**Issue by paigemork** [NETL-RIC/GISA-testing-issues#15]
**Is your feature request related to a problem? Please describe.**
Layers section is small and difficult to view what has been selected. 

**Describe the solution you'd like**
Would be great if upper bar containing Layers list could be larger in height to enable scrolling through layers more easily and seeing what has been selected already more easily.

**Comment by justaPCWingo** [comment]
It may make sense to use a different widget (A checkable dropdown list), or a separate dialog altogether. The latter could be a series of checkboxes (as in STA), or could be a table where each row has a checkbox and a title, where selecting  a row brings up a layer description.

Or something else. Just some thoughts

**Comment by michael-c-gao** [comment]
@justaPCWingo Is the checkable dropdown a builtin or a custom widget?

**Comment by justaPCWingo** [comment]
@michael-c-gao sorry missed this last week. I need to fix some email filters...

anyway, a drop down is a ComboBox in Qt (its one of those widgets that each library gives a different name). I thought that making entries checkable was an option with the base widget, but it looks like you need to do a little [model/view work](https://doc.qt.io/qt-6/qcombobox.html#model-view-framework) to get it to behave properly.

**Comment by michael-c-gao** [comment]
made area larger
