### ISSUE TITLE
Map not displaying with simple cluster

### ISSUE THREAD

**Issue by irpfander** [NETL-RIC/GISA-testing-issues#3]
**Describe the bug**
Map not displaying after selecting simple cluster and display data. I was able to recreate this twice.

**To Reproduce**
1. selected data: WI_Power_Plant_Outfalls_processed2.csv
2. set lat/lon
3.  selected simple cluster and plot data
4. map took several minutes to load, then disappeared 

**Screenshots**
<img width="505" alt="Capture" src="https://github.com/NETL-RIC/GISA-testing-issues/assets/59677370/53ac631c-2bf9-43f6-9163-bcfbed3cf70b">

**Comment by michael-c-gao** [comment]
@irpfander How many lines does the csv have?

**Comment by irpfander** [comment]
After waiting 5 more minutes, the map displays! The csv has 186,681 rows, probably just slow to display @michael-c-gao
