### ISSUE TITLE
Add name of selected file in the Location tab 

### ISSUE THREAD

**Issue by irpfander** [NETL-RIC/GISA-testing-issues#4]
It would be helpful to see the selected file name displayed in the Location tab, potentially above the Select Data button adding text like "Selected File: C:/Users...file.csv" or "Selected File: file.csv"

This addition would be similar to how the path is displayed in the File Content tab "Search Directory: C:/Users..."

**Comment by michael-c-gao** [comment]
added, selected file now displays above select file button
