### ISSUE TITLE
K---Anonymization - Out of Bounds Error

### ISSUE THREAD

**Issue by schooleyc** [NETL-RIC/GISA-testing-issues#6]
**Describe the bug**
For groundwater monitoring wells in Alabama, LSH Anonymization works fine, but a command error occurs when trying to use K---Anonymization 

**To Reproduce**
1. Go to the 'Location tab'
2. Add CSV file with lat/lon
3. Click the 'K---Anonymization' radio button
4. Click 'Plot data'
5. See error; js: Uncaught Error: Bounds are not valid.

**Expected behavior**
I wasn't sure what to expect, but assumed points or clusters would appear on the map like the other radio button choices created

**Screenshots**

** Stack Trace **
     Unnamed: 0 AgencyCd  ...               SitePID                                           USGSLink
0             0     GSAL  ...           GSAL_125344  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
1             1     GSAL  ...           GSAL_100834  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
2             2     GSAL  ...            GSAL_92197  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
3             3     GSAL  ...           GSAL_119719  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
4             4     GSAL  ...           GSAL_119833  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
..          ...      ...  ...                   ...                                                ...
241         241     USGS  ...  USGS_345222086303301  https://cida.usgs.gov/ngwmn/provider/USGS/site...
242         242     USGS  ...  USGS_345822086254001  https://cida.usgs.gov/ngwmn/provider/USGS/site...
243         243     USGS  ...  USGS_325159086423801  https://cida.usgs.gov/ngwmn/provider/USGS/site...
244         244     USGS  ...  USGS_345912086243901  https://cida.usgs.gov/ngwmn/provider/USGS/site...
245         245     USGS  ...  USGS_324340087350501  https://cida.usgs.gov/ngwmn/provider/USGS/site...

[246 rows x 49 columns]
     Unnamed: 0 AgencyCd  ...               SitePID                                           USGSLink
0             0     GSAL  ...           GSAL_125344  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
1             1     GSAL  ...           GSAL_100834  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
2             2     GSAL  ...            GSAL_92197  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
3             3     GSAL  ...           GSAL_119719  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
4             4     GSAL  ...           GSAL_119833  https://cida.usgs.gov/ngwmn/provider/GSAL/site...
..          ...      ...  ...                   ...                                                ...
241         241     USGS  ...  USGS_345222086303301  https://cida.usgs.gov/ngwmn/provider/USGS/site...
242         242     USGS  ...  USGS_345822086254001  https://cida.usgs.gov/ngwmn/provider/USGS/site...
243         243     USGS  ...  USGS_325159086423801  https://cida.usgs.gov/ngwmn/provider/USGS/site...
244         244     USGS  ...  USGS_345912086243901  https://cida.usgs.gov/ngwmn/provider/USGS/site...
245         245     USGS  ...  USGS_324340087350501  https://cida.usgs.gov/ngwmn/provider/USGS/site...

[246 rows x 49 columns]
c
js: Uncaught Error: Bounds are not valid.

**Additional context**
Location of csv on GAIA: P:\01_DataOriginals\USA\Groundwater\NGWMN_Data_102022\01_Working\Alabama\Alabama_SITE_INFO_NAD83.csv

**Comment by michael-c-gao** [comment]
Currently K anonymization is not implemented. I should probably remove that option from the tool
