### ISSUE TITLE
Crash when adding shapefile

### ISSUE THREAD

**Issue by schooleyc** [NETL-RIC/GISA-testing-issues#8]
**Describe the bug**
When I tried to add 'P:\02_DataWorking\USA\Groundwater\aquiferp025.shp' the application crashed. 

**To Reproduce**
1. Go to 'Select Data'
2. Click on the shapefile (see screenshot). Only the .shp exists as an option
3. Application crashes

**Expected behavior**
I expected a polygon to show up on the map and some sort of anonymizing options to be available

**Screenshots**
![image](https://github.com/NETL-RIC/GISA-testing-issues/assets/111004612/60483b1b-d3f6-4990-babd-752bd61869a5)

![image](https://github.com/NETL-RIC/GISA-testing-issues/assets/111004612/3d2280b9-8f0f-44ee-918e-d055e828bd68)

** Stack Trace **
Traceback
Traceback (most recent call last):
  File "gisalib\ui_qt\location_tab.py", line 271, in _load_data
  File "gisalib\controllers\location_controller.py", line 42, in load_dataframe_from_file
AttributeError: 'Polygon' object has no attribute 'x'

**Additional context**
Shapefile shows up fine in ArcGIS Pro, but when you look at a shapefile file in ArcGIS Pro, it bundles all those other file extensions (.prj, .prx, etc.) for you and looks like one file. I tried adding the shapefile from GAIA and from my local drive.

**Comment by michael-c-gao** [comment]
@schooleyc Could you send me the shapefiles? I am unable to access the P drive.

**Comment by michael-c-gao** [comment]
@schooleyc Was there any error msg that was generated?

**Comment by michael-c-gao** [comment]
@schooleyc What data/image is contained within the shapefile? Is it a collection of points or something else?

**Comment by michael-c-gao** [comment]
I think the issue here is that the tool is only able to load and anonymize shapefiles with point data, not polygon data. I can add an exception for polygons where it throws a warning message to the user that it is not able to do this but would like to confirm first.

**Comment by schooleyc** [comment]
@michael-c-gao Where would you like me to send the shapefile to? An email, EDX, etc.?
The data in the shapefile is a polygon of aquifers in the US
If the tool is only able to anonymize point shapefiles I think a warning message should be thrown for polygon and polyline shapefiles. It should also be stated in the documentation that it is only point shapefiles.

**Comment by michael-c-gao** [comment]
@schooleyc I was able to access the data and have now added a warning message that indicates to the user that it is only able to work with point shapefiles. @paigemork Is this something you can add to the documentation?

**Comment by paigemork** [comment]
Edited user documentation to reflect

**Comment by michael-c-gao** [comment]
Thanks all!
