### ISSUE TITLE
Ability to flip back and forth easily between Raw and anonymized/Plotted point data

### ISSUE THREAD

**Issue by paigemork** [NETL-RIC/GISA-testing-issues#9]
I recommend we consider adding functionality that enables a user to flip between the Raw Data file and the LSK/Cluster/or Buffer Anonymization data once run. This would enable a user to compare the original and plotted/anonymized data in real time without having to wait for the tool to run the analysis again whenever they want to go back to the anonymized data. 

Not sure exactly how to implement, but perhaps just selecting the Raw Data without pressing "Plot Data" would just revert it back automatically it it was already at one point loaded or plotted with that technique.

**Comment by justaPCWingo** [comment]
I have a version of this implemented that will be checked in with my other changes
